flags: {}
extra-package-dbs: []
packages:
- '.'
- codec-jvm
- libraries/eta-boot
- libraries/eta-boot-th
- utils/eta-pkg
- etlas/etlas
- etlas/etlas-cabal
- etlas/hackage-security/hackage-security
- shake
extra-deps:
- aeson-1.0.2.1
- mmorph-1.0.9
- optparse-applicative-0.13.0.0
- turtle-1.3.0
- unix-compat-0.4.3.1
- zip-0.1.8
- cryptohash-sha256-0.11.100.1
- echo-0.1.3
- hackage-security-0.5.2.2
- ed25519-0.0.5.0
- binary-0.8.4.1
resolver: lts-6.27
