flags: {}
extra-package-dbs: []
packages:
- '.'
- codec-jvm
- utils/ghcvm-pkgdb # TODO: Shift this to libraries/
- utils/ghcvm-pkg
extra-deps:
- control-monad-exception-0.11.2
- failure-0.2.0.3
- text-1.2.2.1
resolver: lts-6.6
